theme: jekyll-theme-minimal
title: Ritika Avadhanula
logo: <img src="Ritika_Avadhanula_Photograph"/>
description: Hey! My name is Ritika. I am an Robotics Software Engineer with a background in Motion Planning and Controls. Most recently I had the pleasure to work with Sirab Technologies as their GNC engineer. Weather for work or for pleasure I love exploring ideas that enhance people's quality of live
